### PR TITLE
Setup appveyor

### LINKED ISSUE #40: Segfault on windows 10 with cffi
The segfault is shown https://ci.appveyor.com/project/itziakos/pywin32-ctypes/build/1.0.21/job/2t7qda654rqf72dh. 

The segfault can be replicated by running the `test_read_simple` test in `TestCred`. I was able to replicate locally with Windows 10 and python 3.4 and 2.7.

It looks that there is a problem when calling CredRead (https://github.com/enthought/pywin32-ctypes/blob/master/win32ctypes/pywin32/win32cred.py#L46)

### PR DESCRIPTION
**Pull request by itziakos**
provides #19 and fixes #40

### CODE REVIEW

**Comment by itziakos** [comment]
it looks that there is a problem with `cffi 1.3.1` it might be the pypi wheel, we need to investigate (#40).

**Comment by itziakos** [comment]
@cournape please have a look

**Comment by itziakos** [comment]
@cournape  please have a look

**Comment by Juanlu001** [comment]
Are there any links to the AppVeyor builds?

**Comment by itziakos** [comment]
They should be here https://ci.appveyor.com/project/itziakos/pywin32-ctypes they should also be visible  on PRs in github. I forgot to add the link to readme

**Pull request merged**
