### PR TITLE
Cffi wrappers

### PR DESCRIPTION
**Pull request by itziakos**
requires #30 to be merged before

### CODE REVIEW

**Comment by itziakos** [comment]
@cournape, this PR is ready for review

**Comment by itziakos** [comment]
finally the tests pass.

**Comment by cournape** [comment]
LGTM.

I have not looked at the details, but the new cffi >= 1.0 has some interesting improvements regarding code organization and import speed (see also https://cffi.readthedocs.org/en/latest/overview.html)

We have the latest cffi in our repo FWIW (1.0.3 as we speak)

**Comment by cournape** [comment]
Actually, it would be good to mention cffi in the README.

It would also be good to consider testing pypy (without pywin32 of course).

**Comment by itziakos** [comment]
> It would also be good to consider testing pypy (without pywin32 of course).

Since it will require to have a new set of tests. I think that it should be part of a new PR. Is that ok?

**Comment by itziakos** [comment]
> I have not looked at the details, but the new cffi >= 1.0 has some interesting improvements regarding code organization and import speed (see also https://cffi.readthedocs.org/en/latest/overview.html)

Yes, there is a new way of providing ABI access to dlls but I think it requires a compiler.

**Comment by itziakos** [comment]
@cournape I have updated the readme and cleanedup the CI builts. I also added an issue about testing without pywin32. Please have another look

**Comment by itziakos** [comment]
@cournape is this ok to merge?

**Comment by itziakos** [comment]
@cournape ping

**Comment by cournape** [comment]
LGTM

**Pull request merged**
